"""Phase 20A — Sovereign Audit Trail UI.

Provides a self-contained, dark-themed HTML page served at GET /audit.
The page fetches live data from three API endpoints and auto-refreshes
every 10 seconds.  No external dependencies — pure HTML / CSS / JS.
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# The complete audit-trail page as a module-level constant.
# This string is intentionally kept on multiple lines for readability.
# ---------------------------------------------------------------------------

AUDIT_HTML: str = (
    "<!DOCTYPE html>"
    "\n<html lang=\"en\">"
    "\n<head>"
    "\n  <meta charset=\"UTF-8\">"
    "\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    "\n  <title>PRADY OS -- Audit Trail</title>"
    "\n  <style>"
    "\n    * { box-sizing: border-box; margin: 0; padding: 0; }"
    "\n    body { background: #0a0a0f; color: #e0e0f0; font-family: 'Courier New', monospace; }"
    "\n    header { background: #12121e; border-bottom: 1px solid #2a2a4a; padding: 1rem 2rem;"
    "\n             display: flex; align-items: center; justify-content: space-between; }"
    "\n    header h1 { font-size: 1.4rem; color: #7b8fff; letter-spacing: 2px; }"
    "\n    header .badge { font-size: 0.75rem; color: #4caf50; border: 1px solid #4caf50;"
    "\n                    padding: 2px 8px; border-radius: 4px; }"
    "\n    main { padding: 2rem; max-width: 1400px; margin: 0 auto; }"
    "\n    .section { margin-bottom: 2rem; }"
    "\n    .section h2 { font-size: 0.9rem; color: #7b8fff; text-transform: uppercase;"
    "\n                  letter-spacing: 2px; margin-bottom: 0.8rem;"
    "\n                  border-bottom: 1px solid #2a2a4a; padding-bottom: 0.4rem; }"
    "\n    .tbl-wrap { overflow-x: auto; }"
    "\n    table { width: 100%; border-collapse: collapse; font-size: 0.8rem; }"
    "\n    thead tr { background: #12121e; }"
    "\n    th { text-align: left; padding: 6px 10px; color: #7b8fff;"
    "\n         border-bottom: 1px solid #2a2a4a; white-space: nowrap; }"
    "\n    td { padding: 5px 10px; border-bottom: 1px solid #1a1a2e;"
    "\n         color: #c0c0e0; vertical-align: top; word-break: break-word; }"
    "\n    tbody tr:hover { background: #14142a; }"
    "\n    .empty { color: #444466; font-style: italic; padding: 8px 10px; }"
    "\n    .ts { color: #6a8a9a; font-size: 0.75rem; }"
    "\n    .tag { display: inline-block; background: #1e1e3a; border: 1px solid #3a3a5a;"
    "\n           border-radius: 3px; padding: 1px 5px; font-size: 0.72rem;"
    "\n           color: #a0a0d0; margin: 1px; }"
    "\n    #refresh-info { font-size: 0.75rem; color: #444466; }"
    "\n    .nav-link { font-size: 0.8rem; color: #7b8fff; text-decoration: none;"
    "\n                border: 1px solid #2a2a4a; padding: 2px 10px; border-radius: 4px; }"
    "\n    .nav-link:hover { background: #12121e; }"
    "\n  </style>"
    "\n</head>"
    "\n<body>"
    "\n  <header>"
    "\n    <h1>PRADY OS — AUDIT TRAIL</h1>"
    "\n    <div style=\"display:flex;align-items:center;gap:1rem;\">"
    "\n      <a href=\"/\" class=\"nav-link\">← Dashboard</a>"
    "\n      <span id=\"refresh-info\">Auto-refresh: 10s</span>"
    "\n      <span class=\"badge\" id=\"status-badge\">LIVE</span>"
    "\n    </div>"
    "\n  </header>"
    "\n  <main>"
    "\n"
    "\n    <!-- ===== Event Ledger ===== -->"
    "\n    <div class=\"section\" id=\"section-ledger\">"
    "\n      <h2>Event Ledger</h2>"
    "\n      <div class=\"tbl-wrap\">"
    "\n        <table id=\"ledger-table\">"
    "\n          <thead><tr>"
    "\n            <th>#</th><th>Timestamp</th><th>Service</th>"
    "\n            <th>Event</th><th>Payload</th><th>Hash</th>"
    "\n          </tr></thead>"
    "\n          <tbody id=\"ledger-body\">"
    "\n            <tr><td colspan=\"6\" class=\"empty\">Loading…</td></tr>"
    "\n          </tbody>"
    "\n        </table>"
    "\n      </div>"
    "\n    </div>"
    "\n"
    "\n    <!-- ===== Telemetry Spans ===== -->"
    "\n    <div class=\"section\" id=\"section-telemetry\">"
    "\n      <h2>Telemetry Spans</h2>"
    "\n      <div class=\"tbl-wrap\">"
    "\n        <table id=\"telemetry-table\">"
    "\n          <thead><tr>"
    "\n            <th>Span ID</th><th>Trace ID</th><th>Name</th>"
    "\n            <th>Service</th><th>Start</th><th>Duration (ms)</th><th>Status</th>"
    "\n          </tr></thead>"
    "\n          <tbody id=\"telemetry-body\">"
    "\n            <tr><td colspan=\"7\" class=\"empty\">Loading…</td></tr>"
    "\n          </tbody>"
    "\n        </table>"
    "\n      </div>"
    "\n    </div>"
    "\n"
    "\n    <!-- ===== Intent Suggestions ===== -->"
    "\n    <div class=\"section\" id=\"section-intent\">"
    "\n      <h2>Intent Suggestions</h2>"
    "\n      <div class=\"tbl-wrap\">"
    "\n        <table id=\"intent-table\">"
    "\n          <thead><tr>"
    "\n            <th>Action</th><th>Priority</th><th>Reason</th><th>Rule</th><th>Params</th>"
    "\n          </tr></thead>"
    "\n          <tbody id=\"intent-body\">"
    "\n            <tr><td colspan=\"5\" class=\"empty\">Loading…</td></tr>"
    "\n          </tbody>"
    "\n        </table>"
    "\n      </div>"
    "\n    </div>"
    "\n"
    "\n  </main>"
    "\n  <script>"
    "\n    // ----------------------------------------------------------------"
    "\n    // Helpers"
    "\n    // ----------------------------------------------------------------"
    "\n    function fmtTs(ts) {"
    "\n      if (!ts && ts !== 0) return 'n/a';"
    "\n      try { return new Date(ts * 1000).toISOString().replace('T',' ').slice(0,23); }"
    "\n      catch(e) { return String(ts); }"
    "\n    }"
    "\n    function fmtJson(obj) {"
    "\n      if (obj === null || obj === undefined) return '';"
    "\n      if (typeof obj === 'string') return obj;"
    "\n      try { return JSON.stringify(obj); } catch(e) { return String(obj); }"
    "\n    }"
    "\n    function shortHash(h) {"
    "\n      if (!h) return '';"
    "\n      return '<span class=\"tag\">' + String(h).slice(0,12) + '</span>';"
    "\n    }"
    "\n    function noData(cols) {"
    "\n      return '<tr><td colspan=\"' + cols + '\" class=\"empty\">No data</td></tr>';"
    "\n    }"
    "\n"
    "\n    // ----------------------------------------------------------------"
    "\n    // Fetch and render Event Ledger"
    "\n    // ----------------------------------------------------------------"
    "\n    async function fetchLedger() {"
    "\n      try {"
    "\n        const r = await fetch('/api/v1/ledger?limit=20');"
    "\n        if (!r.ok) { throw new Error('HTTP ' + r.status); }"
    "\n        const d = await r.json();"
    "\n        const entries = Array.isArray(d.entries) ? d.entries.slice(-20).reverse() : [];"
    "\n        const tbody = document.getElementById('ledger-body');"
    "\n        if (entries.length === 0) { tbody.innerHTML = noData(6); return; }"
    "\n        tbody.innerHTML = entries.map(function(e, i) {"
    "\n          return '<tr>'"
    "\n            + '<td class=\"ts\">' + (i + 1) + '</td>'"
    "\n            + '<td class=\"ts\">' + fmtTs(e.ts || e.timestamp) + '</td>'"
    "\n            + '<td><span class=\"tag\">' + (e.service || '') + '</span></td>'"
    "\n            + '<td>' + (e.event || '') + '</td>'"
    "\n            + '<td style=\"max-width:300px;overflow:hidden;text-overflow:ellipsis\">' + fmtJson(e.payload) + '</td>'"
    "\n            + '<td>' + shortHash(e.hash) + '</td>'"
    "\n            + '</tr>';"
    "\n        }).join('');"
    "\n      } catch(e) {"
    "\n        document.getElementById('ledger-body').innerHTML ="
    "\n          '<tr><td colspan=\"6\" class=\"empty\">Error: ' + e.message + '</td></tr>';"
    "\n      }"
    "\n    }"
    "\n"
    "\n    // ----------------------------------------------------------------"
    "\n    // Fetch and render Telemetry Spans"
    "\n    // ----------------------------------------------------------------"
    "\n    async function fetchTelemetry() {"
    "\n      try {"
    "\n        const r = await fetch('/api/v1/telemetry');"
    "\n        if (!r.ok) { throw new Error('HTTP ' + r.status); }"
    "\n        const d = await r.json();"
    "\n        const spans = Array.isArray(d.spans) ? d.spans.slice(-20).reverse() : [];"
    "\n        const tbody = document.getElementById('telemetry-body');"
    "\n        if (spans.length === 0) { tbody.innerHTML = noData(7); return; }"
    "\n        tbody.innerHTML = spans.map(function(s) {"
    "\n          const dur = (s.duration_ms !== undefined && s.duration_ms !== null)"
    "\n            ? Number(s.duration_ms).toFixed(2)"
    "\n            : (s.end_time && s.start_time ? ((s.end_time - s.start_time)*1000).toFixed(2) : 'n/a');"
    "\n          return '<tr>'"
    "\n            + '<td class=\"ts\">' + shortHash(s.span_id) + '</td>'"
    "\n            + '<td class=\"ts\">' + shortHash(s.trace_id) + '</td>'"
    "\n            + '<td>' + (s.name || s.operation_name || '') + '</td>'"
    "\n            + '<td><span class=\"tag\">' + (s.service || s.service_name || '') + '</span></td>'"
    "\n            + '<td class=\"ts\">' + fmtTs(s.start_time) + '</td>'"
    "\n            + '<td style=\"text-align:right\">' + dur + '</td>'"
    "\n            + '<td><span class=\"tag\">' + (s.status || 'ok') + '</span></td>'"
    "\n            + '</tr>';"
    "\n        }).join('');"
    "\n      } catch(e) {"
    "\n        document.getElementById('telemetry-body').innerHTML ="
    "\n          '<tr><td colspan=\"7\" class=\"empty\">Error: ' + e.message + '</td></tr>';"
    "\n      }"
    "\n    }"
    "\n"
    "\n    // ----------------------------------------------------------------"
    "\n    // Fetch and render Intent Suggestions (POST /api/v1/intent/suggest)"
    "\n    // ----------------------------------------------------------------"
    "\n    async function fetchIntentSuggestions() {"
    "\n      try {"
    "\n        const r = await fetch('/api/v1/intent/suggest', {"
    "\n          method: 'POST',"
    "\n          headers: { 'Content-Type': 'application/json' },"
    "\n          body: '{}'"
    "\n        });"
    "\n        if (!r.ok) { throw new Error('HTTP ' + r.status); }"
    "\n        const d = await r.json();"
    "\n        const suggs = Array.isArray(d.suggestions) ? d.suggestions.slice(0,20) : [];"
    "\n        const tbody = document.getElementById('intent-body');"
    "\n        if (suggs.length === 0) { tbody.innerHTML = noData(5); return; }"
    "\n        tbody.innerHTML = suggs.map(function(s) {"
    "\n          return '<tr>'"
    "\n            + '<td>' + (s.action || '') + '</td>'"
    "\n            + '<td style=\"text-align:right\">' + (s.priority !== undefined ? s.priority : '') + '</td>'"
    "\n            + '<td>' + (s.reason || '') + '</td>'"
    "\n            + '<td><span class=\"tag\">' + (s.rule || '') + '</span></td>'"
    "\n            + '<td style=\"max-width:260px;overflow:hidden;text-overflow:ellipsis\">' + fmtJson(s.params) + '</td>'"
    "\n            + '</tr>';"
    "\n        }).join('');"
    "\n      } catch(e) {"
    "\n        document.getElementById('intent-body').innerHTML ="
    "\n          '<tr><td colspan=\"5\" class=\"empty\">Error: ' + e.message + '</td></tr>';"
    "\n      }"
    "\n    }"
    "\n"
    "\n    // ----------------------------------------------------------------"
    "\n    // Refresh all sections"
    "\n    // ----------------------------------------------------------------"
    "\n    function refreshAll() {"
    "\n      fetchLedger();"
    "\n      fetchTelemetry();"
    "\n      fetchIntentSuggestions();"
    "\n      const now = new Date().toLocaleTimeString();"
    "\n      document.getElementById('refresh-info').textContent = 'Last refresh: ' + now;"
    "\n    }"
    "\n"
    "\n    refreshAll();"
    "\n    setInterval(refreshAll, 10000);"
    "\n  </script>"
    "\n</body>"
    "\n</html>"
)


def build_audit_html() -> str:
    """Return the complete Audit Trail HTML page string.

    This function is provided for testability.  It always returns the
    module-level ``AUDIT_HTML`` constant — deterministic and idempotent.
    """
    return AUDIT_HTML
